In [1]:
import pandas as pd
import pandera as pa

In [2]:
df = pd.read_csv('file.csv', parse_dates=['ocorrencia_data'], dayfirst=True)

In [3]:
df.replace(['None'], pd.NA, inplace=True)
df.fillna(0, inplace=True)

In [4]:
df.replace([0], pd.NA, inplace=True)
df

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_data,ocorrencia_horario
0,1,11,<NA>,Rio de Janeiro,RJ,<NA>,2022-11-01,14:30
1,2,22,Acidente,São Paulo,SP,SBSP,2022-01-02,10:15
2,3,33,Incidente,Belo Horizonte,MG,<NA>,2022-01-03,08:45
3,4,44,Acidente,Recife,PE,SBRF,2022-01-04,16:20
4,5,55,Incidente,Brasília,DF,SBBR,2022-01-05,12:10
5,6,66,Acidente,Porto Alegre,RS,<NA>,2022-01-06,09:05
6,7,77,Incidente,Curitiba,PR,SBCT,2022-01-07,18:30
7,8,88,Acidente,Salvador,BA,SBSV,2022-01-08,11:40
8,9,99,Incidente,Manaus,AM,<NA>,2022-01-09,13:25
9,10,1010,Acidente,Goiânia,GO,SBGO,2022-01-10,15:50
10,10,1010,Acidente,Goiânia,GO,SBGO,2022-01-10,15:50

In [5]:
df.fillna(value={'ocorrencia_aerodromo': 69})

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_data,ocorrencia_horario
0,1,11,<NA>,Rio de Janeiro,RJ,69,2022-11-01,14:30
1,2,22,Acidente,São Paulo,SP,SBSP,2022-01-02,10:15
2,3,33,Incidente,Belo Horizonte,MG,69,2022-01-03,08:45
3,4,44,Acidente,Recife,PE,SBRF,2022-01-04,16:20
4,5,55,Incidente,Brasília,DF,SBBR,2022-01-05,12:10
5,6,66,Acidente,Porto Alegre,RS,69,2022-01-06,09:05
6,7,77,Incidente,Curitiba,PR,SBCT,2022-01-07,18:30
7,8,88,Acidente,Salvador,BA,SBSV,2022-01-08,11:40
8,9,99,Incidente,Manaus,AM,69,2022-01-09,13:25
9,10,1010,Acidente,Goiânia,GO,SBGO,2022-01-10,15:50
10,10,1010,Acidente,Goiânia,GO,SBGO,2022-01-10,15:50

In [6]:
df['horario_2'] = df.ocorrencia_horario
df

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_data,ocorrencia_horario,horario_2
0,1,11,<NA>,Rio de Janeiro,RJ,<NA>,2022-11-01,14:30,14:30
1,2,22,Acidente,São Paulo,SP,SBSP,2022-01-02,10:15,10:15
2,3,33,Incidente,Belo Horizonte,MG,<NA>,2022-01-03,08:45,08:45
3,4,44,Acidente,Recife,PE,SBRF,2022-01-04,16:20,16:20
4,5,55,Incidente,Brasília,DF,SBBR,2022-01-05,12:10,12:10
5,6,66,Acidente,Porto Alegre,RS,<NA>,2022-01-06,09:05,09:05
6,7,77,Incidente,Curitiba,PR,SBCT,2022-01-07,18:30,18:30
7,8,88,Acidente,Salvador,BA,SBSV,2022-01-08,11:40,11:40
8,9,99,Incidente,Manaus,AM,<NA>,2022-01-09,13:25,13:25
9,10,1010,Acidente,Goiânia,GO,SBGO,2022-01-10,15:50,15:50
10,10,1010,Acidente,Goiânia,GO,SBGO,2022-01-10,15:50,15:50

In [7]:
df.drop(['horario_2'], axis=1, inplace=True)

In [8]:
df

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_data,ocorrencia_horario
0,1,11,<NA>,Rio de Janeiro,RJ,<NA>,2022-11-01,14:30
1,2,22,Acidente,São Paulo,SP,SBSP,2022-01-02,10:15
2,3,33,Incidente,Belo Horizonte,MG,<NA>,2022-01-03,08:45
3,4,44,Acidente,Recife,PE,SBRF,2022-01-04,16:20
4,5,55,Incidente,Brasília,DF,SBBR,2022-01-05,12:10
5,6,66,Acidente,Porto Alegre,RS,<NA>,2022-01-06,09:05
6,7,77,Incidente,Curitiba,PR,SBCT,2022-01-07,18:30
7,8,88,Acidente,Salvador,BA,SBSV,2022-01-08,11:40
8,9,99,Incidente,Manaus,AM,<NA>,2022-01-09,13:25
9,10,1010,Acidente,Goiânia,GO,SBGO,2022-01-10,15:50
10,10,1010,Acidente,Goiânia,GO,SBGO,2022-01-10,15:50

In [9]:
df.drop_duplicates(inplace=True)
df.fillna(0, inplace=True)